// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fafqbzjpeezdzgtibmcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhZnFiempwZWV6ZHpndGlibWN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0OTY1NDQsImV4cCI6MjA3MzA3MjU0NH0.ft4n4WndeMNvedNW-0yYLOcY0pMyVhxwuw7SkgFfip0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});